name: decorator_annotation
description: A new Flutter package.
version: 0.0.1
author: Eugene Ostashko <ostashko4@gmail.com>
homepage: https://github.com/ReliableCauliflower/decorator

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^0.9.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter